# Generated by Django 5.2.8 on 2025-12-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('LS', 'Life Sciences (Biology, Biotech, Pharma)'), ('NS', 'Natural Sciences (Chemistry, Physics, Math)'), ('ES', 'Environmental Science / Conservation'), ('QC', 'Quality Control / Assurance')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('is_internship', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='accounts.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Reviewed'), ('I', 'Interview'), ('H', 'Hired'), ('X', 'Rejected')], default='P', max_length=1)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.studentprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.jobpost')),
            ],
            options={
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
